### PR TITLE
Fixing the `process.cwd` reference to properly invoke the function

### PR DESCRIPTION
**Pull request by BenAHammond**
… Adding safety checks to the _HANDLER ENV variable to prevent errors running in mocked contexts for testing.

### CODE REVIEW

**Comment by BenAHammond** [comment]
If no one is maintaining this repo I will just maintain my fork separately

**Comment by shortjared** [comment]
Hi @BenAHammond, we'll get to this in the next couple days. Looks pretty simple and safe.

**Comment by BenAHammond** [comment]
Oh, great, I just wasn't sure anyone was around. Thanks!

**Comment by shortjared** [comment]
@azurelogic

**Comment by azurelogic** [comment]
LGTM

**Comment by azurelogic** [comment]
@BenAHammond Thanks for the contribution! If you find any other items, don't hesitate to send an issue/PR.

**Comment by BenAHammond** [comment]
I appreciate your time!

**Pull request merged**
